// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","menuRender":false,"redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"","path":"/index","menuRender":false,"redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/dashboard","menuRender":false,"parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/admin/dashboard","menuRender":false,"access":"adminAccess","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/login","menuRender":false,"hideInMenu":true,"layout":false,"id":"5"},"6":{"name":"callback","layout":false,"path":"/oauth/callback","id":"6"},"7":{"path":"/*","parentId":"ant-design-pro-layout","id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__openclaw__dashboard" */'@/pages/openclaw/dashboard.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__openclaw__admin-dashboard" */'@/pages/openclaw/admin-dashboard.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__oauth__login" */'@/pages/oauth/login.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__oauth__callback" */'@/pages/oauth/callback.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/cloudy/Documents/efucloud/cloud-claw-manager/web/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
